export const ADD_USER_ADMIN = "ADD_USER_ADMIN"
export const REMOVE_USER_ADMIN = "REMOVE_USER_ADMIN"

export const ADD_STUDY_MOD = "ADD_STUDY_MOD"
export const CLOSE_STUDY_MOD = "CLOSE_STUDY_MOD"
export const REMOVE_STUDY_MOD = "REMOVE_STUDY_MOD"
export const ADD_IMAGE_STUDY_MOD = "ADD_IMAGE_STUDY_MOD"
export const REMOVE_IMAGE_STUDY_MOD = "REMOVE_IMAGE_STUDY_MOD"
export const ADD_CLINICIAN_STUDY_MOD = "ADD_CLINICIAN_STUDY_MOD"
export const ADD_SCORE_STUDY_CLIN ="ADD_SCORE_STUDY_CLIN"

export const ADD_NOTIFICATION = "ADD_NOTIFICATION"


export const ADD_ORGANIZATION_ADMIN = "ADD_ORGANIZATION_ADMIN"
export const ADD_CLINICIAN_ORGANIZATION_ADMIN = "ADD_CLINICIAN_ORGANIZATION_ADMIN"
export const ADD_STUDY_ORGANIZATION_ADMIN = "ADD_STUDY_ORGANIZATION_ADMIN"
export const REMOVE_ORGANIZATION_ADMIN = "REMOVE_ORGANIZATION_ADMIN"